package com.myvideo.dao;

import com.myvideo.model.persistant.LolDyTtGrabErrorPo;
import com.myvideo.model.persistant.LolDyTtGrabErrorPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ILolDyTtGrabErrorDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab_error
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    long countByExample(LolDyTtGrabErrorPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab_error
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    int deleteByExample(LolDyTtGrabErrorPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab_error
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab_error
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    int insert(LolDyTtGrabErrorPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab_error
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    int insertSelective(LolDyTtGrabErrorPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab_error
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    List<LolDyTtGrabErrorPo> selectByExample(LolDyTtGrabErrorPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab_error
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    LolDyTtGrabErrorPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab_error
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    int updateByExampleSelective(@Param("record") LolDyTtGrabErrorPo record, @Param("example") LolDyTtGrabErrorPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab_error
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    int updateByExample(@Param("record") LolDyTtGrabErrorPo record, @Param("example") LolDyTtGrabErrorPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab_error
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    int updateByPrimaryKeySelective(LolDyTtGrabErrorPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab_error
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    int updateByPrimaryKey(LolDyTtGrabErrorPo record);
}