package com.myvideo.dao;

import com.myvideo.model.persistant.LolDyTtMoviePo;
import com.myvideo.model.persistant.LolDyTtMoviePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ILolDyTtMovieDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    long countByExample(LolDyTtMoviePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    int deleteByExample(LolDyTtMoviePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    int insert(LolDyTtMoviePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    int insertSelective(LolDyTtMoviePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    List<LolDyTtMoviePo> selectByExampleWithBLOBs(LolDyTtMoviePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    List<LolDyTtMoviePo> selectByExample(LolDyTtMoviePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    LolDyTtMoviePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    int updateByExampleSelective(@Param("record") LolDyTtMoviePo record, @Param("example") LolDyTtMoviePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    int updateByExampleWithBLOBs(@Param("record") LolDyTtMoviePo record, @Param("example") LolDyTtMoviePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    int updateByExample(@Param("record") LolDyTtMoviePo record, @Param("example") LolDyTtMoviePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    int updateByPrimaryKeySelective(LolDyTtMoviePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    int updateByPrimaryKeyWithBLOBs(LolDyTtMoviePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_movie
     *
     * @mbg.generated 2018-09-16 16:40:15
     */
    int updateByPrimaryKey(LolDyTtMoviePo record);
}