package com.myvideo.dao;

import com.myvideo.model.persistant.LolDyTtGrabPo;
import com.myvideo.model.persistant.LolDyTtGrabPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ILolDyTtGrabDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    long countByExample(LolDyTtGrabPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    int deleteByExample(LolDyTtGrabPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    int insert(LolDyTtGrabPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    int insertSelective(LolDyTtGrabPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    List<LolDyTtGrabPo> selectByExample(LolDyTtGrabPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    LolDyTtGrabPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    int updateByExampleSelective(@Param("record") LolDyTtGrabPo record, @Param("example") LolDyTtGrabPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    int updateByExample(@Param("record") LolDyTtGrabPo record, @Param("example") LolDyTtGrabPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    int updateByPrimaryKeySelective(LolDyTtGrabPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    int updateByPrimaryKey(LolDyTtGrabPo record);
}