package com.myvideo.model.persistant;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_loldytt_grab_error
 */
public class LolDyTtGrabErrorPo {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loldytt_grab_error.id
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   页面地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loldytt_grab_error.page_url
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    private String pageUrl;

    /**
     * Database Column Remarks:
     *   错误信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loldytt_grab_error.msg
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    private String msg;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loldytt_grab_error.create_time
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loldytt_grab_error.id
     *
     * @return the value of t_loldytt_grab_error.id
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loldytt_grab_error.id
     *
     * @param id the value for t_loldytt_grab_error.id
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loldytt_grab_error.page_url
     *
     * @return the value of t_loldytt_grab_error.page_url
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    public String getPageUrl() {
        return pageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loldytt_grab_error.page_url
     *
     * @param pageUrl the value for t_loldytt_grab_error.page_url
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl == null ? null : pageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loldytt_grab_error.msg
     *
     * @return the value of t_loldytt_grab_error.msg
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loldytt_grab_error.msg
     *
     * @param msg the value for t_loldytt_grab_error.msg
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loldytt_grab_error.create_time
     *
     * @return the value of t_loldytt_grab_error.create_time
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loldytt_grab_error.create_time
     *
     * @param createTime the value for t_loldytt_grab_error.create_time
     *
     * @mbg.generated 2018-09-15 14:49:26
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}