package com.myvideo.model.persistant;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LolDyTtGrabPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public LolDyTtGrabPoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumIsNull() {
            addCriterion("last_total_page_num is null");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumIsNotNull() {
            addCriterion("last_total_page_num is not null");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumEqualTo(Integer value) {
            addCriterion("last_total_page_num =", value, "lastTotalPageNum");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumNotEqualTo(Integer value) {
            addCriterion("last_total_page_num <>", value, "lastTotalPageNum");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumGreaterThan(Integer value) {
            addCriterion("last_total_page_num >", value, "lastTotalPageNum");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_total_page_num >=", value, "lastTotalPageNum");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumLessThan(Integer value) {
            addCriterion("last_total_page_num <", value, "lastTotalPageNum");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumLessThanOrEqualTo(Integer value) {
            addCriterion("last_total_page_num <=", value, "lastTotalPageNum");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumIn(List<Integer> values) {
            addCriterion("last_total_page_num in", values, "lastTotalPageNum");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumNotIn(List<Integer> values) {
            addCriterion("last_total_page_num not in", values, "lastTotalPageNum");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumBetween(Integer value1, Integer value2) {
            addCriterion("last_total_page_num between", value1, value2, "lastTotalPageNum");
            return (Criteria) this;
        }

        public Criteria andLastTotalPageNumNotBetween(Integer value1, Integer value2) {
            addCriterion("last_total_page_num not between", value1, value2, "lastTotalPageNum");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumIsNull() {
            addCriterion("last_grab_page_num is null");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumIsNotNull() {
            addCriterion("last_grab_page_num is not null");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumEqualTo(Integer value) {
            addCriterion("last_grab_page_num =", value, "lastGrabPageNum");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumNotEqualTo(Integer value) {
            addCriterion("last_grab_page_num <>", value, "lastGrabPageNum");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumGreaterThan(Integer value) {
            addCriterion("last_grab_page_num >", value, "lastGrabPageNum");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_grab_page_num >=", value, "lastGrabPageNum");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumLessThan(Integer value) {
            addCriterion("last_grab_page_num <", value, "lastGrabPageNum");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumLessThanOrEqualTo(Integer value) {
            addCriterion("last_grab_page_num <=", value, "lastGrabPageNum");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumIn(List<Integer> values) {
            addCriterion("last_grab_page_num in", values, "lastGrabPageNum");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumNotIn(List<Integer> values) {
            addCriterion("last_grab_page_num not in", values, "lastGrabPageNum");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumBetween(Integer value1, Integer value2) {
            addCriterion("last_grab_page_num between", value1, value2, "lastGrabPageNum");
            return (Criteria) this;
        }

        public Criteria andLastGrabPageNumNotBetween(Integer value1, Integer value2) {
            addCriterion("last_grab_page_num not between", value1, value2, "lastGrabPageNum");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeIsNull() {
            addCriterion("last_grab_start_time is null");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeIsNotNull() {
            addCriterion("last_grab_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeEqualTo(Date value) {
            addCriterion("last_grab_start_time =", value, "lastGrabStartTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeNotEqualTo(Date value) {
            addCriterion("last_grab_start_time <>", value, "lastGrabStartTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeGreaterThan(Date value) {
            addCriterion("last_grab_start_time >", value, "lastGrabStartTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_grab_start_time >=", value, "lastGrabStartTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeLessThan(Date value) {
            addCriterion("last_grab_start_time <", value, "lastGrabStartTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_grab_start_time <=", value, "lastGrabStartTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeIn(List<Date> values) {
            addCriterion("last_grab_start_time in", values, "lastGrabStartTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeNotIn(List<Date> values) {
            addCriterion("last_grab_start_time not in", values, "lastGrabStartTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeBetween(Date value1, Date value2) {
            addCriterion("last_grab_start_time between", value1, value2, "lastGrabStartTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_grab_start_time not between", value1, value2, "lastGrabStartTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeIsNull() {
            addCriterion("last_grab_end_time is null");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeIsNotNull() {
            addCriterion("last_grab_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeEqualTo(Date value) {
            addCriterion("last_grab_end_time =", value, "lastGrabEndTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeNotEqualTo(Date value) {
            addCriterion("last_grab_end_time <>", value, "lastGrabEndTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeGreaterThan(Date value) {
            addCriterion("last_grab_end_time >", value, "lastGrabEndTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_grab_end_time >=", value, "lastGrabEndTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeLessThan(Date value) {
            addCriterion("last_grab_end_time <", value, "lastGrabEndTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_grab_end_time <=", value, "lastGrabEndTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeIn(List<Date> values) {
            addCriterion("last_grab_end_time in", values, "lastGrabEndTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeNotIn(List<Date> values) {
            addCriterion("last_grab_end_time not in", values, "lastGrabEndTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeBetween(Date value1, Date value2) {
            addCriterion("last_grab_end_time between", value1, value2, "lastGrabEndTime");
            return (Criteria) this;
        }

        public Criteria andLastGrabEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_grab_end_time not between", value1, value2, "lastGrabEndTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated do_not_delete_during_merge 2018-09-15 01:13:33
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_loldytt_grab
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}