package com.myvideo.model.persistant;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_loldytt_grab
 */
public class LolDyTtGrabPo {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loldytt_grab.id
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loldytt_grab.type
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    private String type;

    /**
     * Database Column Remarks:
     *   上次获取的该分类总页数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loldytt_grab.last_total_page_num
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    private Integer lastTotalPageNum;

    /**
     * Database Column Remarks:
     *   上次抓取结束的页码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loldytt_grab.last_grab_page_num
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    private Integer lastGrabPageNum;

    /**
     * Database Column Remarks:
     *   上次抓取开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loldytt_grab.last_grab_start_time
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    private Date lastGrabStartTime;

    /**
     * Database Column Remarks:
     *   上次抓取结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loldytt_grab.last_grab_end_time
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    private Date lastGrabEndTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loldytt_grab.id
     *
     * @return the value of t_loldytt_grab.id
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loldytt_grab.id
     *
     * @param id the value for t_loldytt_grab.id
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loldytt_grab.type
     *
     * @return the value of t_loldytt_grab.type
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loldytt_grab.type
     *
     * @param type the value for t_loldytt_grab.type
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loldytt_grab.last_total_page_num
     *
     * @return the value of t_loldytt_grab.last_total_page_num
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public Integer getLastTotalPageNum() {
        return lastTotalPageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loldytt_grab.last_total_page_num
     *
     * @param lastTotalPageNum the value for t_loldytt_grab.last_total_page_num
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public void setLastTotalPageNum(Integer lastTotalPageNum) {
        this.lastTotalPageNum = lastTotalPageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loldytt_grab.last_grab_page_num
     *
     * @return the value of t_loldytt_grab.last_grab_page_num
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public Integer getLastGrabPageNum() {
        return lastGrabPageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loldytt_grab.last_grab_page_num
     *
     * @param lastGrabPageNum the value for t_loldytt_grab.last_grab_page_num
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public void setLastGrabPageNum(Integer lastGrabPageNum) {
        this.lastGrabPageNum = lastGrabPageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loldytt_grab.last_grab_start_time
     *
     * @return the value of t_loldytt_grab.last_grab_start_time
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public Date getLastGrabStartTime() {
        return lastGrabStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loldytt_grab.last_grab_start_time
     *
     * @param lastGrabStartTime the value for t_loldytt_grab.last_grab_start_time
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public void setLastGrabStartTime(Date lastGrabStartTime) {
        this.lastGrabStartTime = lastGrabStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loldytt_grab.last_grab_end_time
     *
     * @return the value of t_loldytt_grab.last_grab_end_time
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public Date getLastGrabEndTime() {
        return lastGrabEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loldytt_grab.last_grab_end_time
     *
     * @param lastGrabEndTime the value for t_loldytt_grab.last_grab_end_time
     *
     * @mbg.generated 2018-09-15 01:13:33
     */
    public void setLastGrabEndTime(Date lastGrabEndTime) {
        this.lastGrabEndTime = lastGrabEndTime;
    }
}